-- Ouvre la place de marché aux rayons non-mode.
-- Purement additif : les six valeurs d'origine restent inchangées, donc les
-- produits déjà en base conservent leur catégorie.

ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'CUISINE';
ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'DECORATION';
ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'MEUBLES';
ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'LINGE_MAISON';
ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'JARDIN_BRICOLAGE';

ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'SOINS_BEAUTE';
ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'PARFUMS';
ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'MAQUILLAGE';
ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'CHEVEUX';

ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'TELEPHONIE';
ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'INFORMATIQUE';
ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'AUDIO_IMAGE';
ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'ELECTROMENAGER';

ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'JOUETS';
ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'PUERICULTURE';
ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'SCOLAIRE';

ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'SPORT_LOISIRS';
ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'LIVRES_MEDIAS';
ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'ANIMAUX';
ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'AUTO_MOTO';

ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'ALIMENTATION';
ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'SANTE';
ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'AUTRE';
